name: ci
permissions:
  contents: read
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install packages via packages.json
        run: make install_ci
      - name: Run textlint
        run: |
          make lint_text
      - name: Run lint
        run: |
          make lint
      - name: Format check
        run: |
          make format_check
      - name: Run test
        env:
          CI: true
          NODE_ENV: test
          EMBEDDING_PROVIDER: ollama
          NOMIC_API_KEY: test-api-key-for-ci
        run: |
          make test
